lank_issues_enabled: true
contact_links:
  - name: Questions & feature requests
    url: https://discord.com/invite/auDgRJqtT9
    about: Questions about the game or feature requests should be discussed in the Discord, not in the issue tracker
